[supervisord]
nodaemon=true
logfile=/var/www/html/storage/logs/supervisord.log
logfile_maxbytes=5MB
logfile_backups=2
loglevel=info
pidfile=/tmp/supervisord.pid

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
priority=10
stdout_logfile=/var/www/html/storage/logs/nginx-stdout.log
stderr_logfile=/var/www/html/storage/logs/nginx-stderr.log
stdout_logfile_maxbytes=5MB
stderr_logfile_maxbytes=5MB

[program:php-fpm]
command=php-fpm -F
autostart=true
autorestart=true
priority=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
