user www-data;
worker_processes auto;
pid /tmp/nginx.pid;
error_log /var/www/html/storage/logs/nginx-error.log warn;

events {
    worker_connections 1024;
    use epoll;
    multi_accept on;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    access_log /var/www/html/storage/logs/nginx-access.log combined buffer=16k;

    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;
    keepalive_timeout 65;
    client_max_body_size 20M;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript;
    gzip_min_length 1000;

    include /etc/nginx/http.d/*.conf;
}
